spring.application.name=clinic
#data
spring.datasource.url=jdbc:mysql://localhost:3306/clinic?
zeroDateTimeBehavior=CONVERT_TO_NULL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
#hibernate
spring.jpa.properties.hibernate.show_sql=true
#spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.hbm2ddl.auto=validate

imgbb.api.key=e7eae9753bad86570c1030ab1fb0a1ce

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.use_sql_comments=false

server.servlet.session.timeout=30m
server.servlet.session.cookie.http-only=true

server.error.path=/error
server.error.whitelabel.enabled=false
server.error.include-stacktrace=never
server.error.include-exception=false
server.error.include-message=always

error.required=???? ??????????? ??? ??????????
error.email=???????? ?????? email
error.phone=???????? ?????? ????????
error.password.min=?????? ?????? ????????? ??????? {min} ????????
error.password.match=?????? ?? ?????????

field.lastName=???????
field.firstName=???
field.patronymic=????????
field.phone=???????
field.email=Email
field.password=??????
field.confirmPassword=????????????? ??????
field.birthDate=???? ????????
field.gender=???

NotBlank.RegistrationDto.lastName={field.lastName} {error.required}
NotBlank.RegistrationDto.firstName={field.firstName} {error.required}
NotBlank.RegistrationDto.phone={field.phone} {error.required}
Pattern.RegistrationDto.phone={field.phone} {error.phone}
NotBlank.RegistrationDto.email={field.email} {error.required}
Email.RegistrationDto.email={field.email} {error.email}
NotBlank.RegistrationDto.password={field.password} {error.required}
Size.RegistrationDto.password={field.password} {error.password.min}
NotBlank.RegistrationDto.confirmPassword={field.confirmPassword} {error.required}
AssertTrue.RegistrationDto.passwordMatch={error.password.match}

email.duplicate=???????????? ? ????? email ??? ??????????
phone.duplicate=???????????? ? ????? ????????? ??? ??????????