spring.application.name=clinic
#data
spring.datasource.url=jdbc:mysql://localhost:3306/clinic?
zeroDateTimeBehavior=CONVERT_TO_NULL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
#hibernate
spring.jpa.properties.hibernate.show_sql=true
#spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.hbm2ddl.auto=validate

imgbb.api.key=e7eae9753bad86570c1030ab1fb0a1ce

# ????????? ????? SQL
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.use_sql_comments=false

server.servlet.session.timeout=30m
server.servlet.session.cookie.http-only=true