spring.application.name=clinic

spring.datasource.url=jdbc:mysql://localhost:3306/course_work?
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:course_work.sql
spring.sql.init.continue-on-error=true
spring.jpa.defer-datasource-initialization=true

zeroDateTimeBehavior=CONVERT_TO_NULL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root

spring.jpa.properties.hibernate.show_sql=true
#spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.hbm2ddl.auto=validate

imgbb.api.key=e7eae9753bad86570c1030ab1fb0a1ce

server.servlet.session.timeout=30m
server.servlet.session.cookie.http-only=true

server.error.path=/error
server.error.whitelabel.enabled=false
server.error.include-stacktrace=never
server.error.include-exception=false
server.error.include-message=always

